parameters: 
environment: 


packages:
  - name: github-sync
    environment: 
    parameters: 
    annotations: 
    functions:
      - name: github-webhook
        binary: false
        main: ""
        runtime: nodejs:18
        web: raw
        webSecure: false
        parameters: 
        environment: 
        annotations: 
        limits: 
          timeout: 900000
          memory: 1024
      - name: batch-sync-overview
        binary: false
        main: ""
        runtime: nodejs:18
        web: raw
        webSecure: false
        parameters: 
        environment: 
        annotations: 
        limits: 
          timeout: 900000
          memory: 1024
